# Generated by Django 3.1.3 on 2022-04-19 07:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('post_idx', models.AutoField(primary_key=True,
                                              serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('pic', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('visualhearing', models.IntegerField()),
                ('post_owner',
                 models.ForeignKey(db_column='id',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Posting',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('chatting_index', models.AutoField(primary_key=True,
                                                    serialize=False)),
                ('username', models.CharField(blank=True,
                                              max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('chatting', models.TextField(null=True)),
                ('post_idx',
                 models.ForeignKey(db_column='post_idx',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='Post.posting')),
            ],
            options={
                'db_table': 'Chatting',
                'managed': True,
            },
        ),
    ]
