# Generated by Django 3.1.3 on 2022-04-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='post_owner',
            new_name='id',
        ),
    ]
