# Generated by Django 3.1.3 on 2022-04-25 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qna_Chatting',
            fields=[
                ('qna_chatting_index', models.AutoField(primary_key=True,
                                                        serialize=False)),
                ('username', models.CharField(blank=True,
                                              max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('chatting', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Qna_Chatting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna_Posting',
            fields=[
                ('qna_idx', models.AutoField(primary_key=True,
                                             serialize=False)),
                ('title', models.CharField(max_length=255,
                                           null=True)),
                ('body', models.TextField(null=True)),
                ('pic', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Qna_Posting',
                'managed': False,
            },
        ),
    ]
