# Generated by Django 3.1.3 on 2022-04-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna_chatting',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qna_posting',
            options={'managed': True},
        ),
    ]
