# Generated by Django 3.1.3 on 2022-04-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qna', '0002_auto_20220425_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qna_Chatting',
        ),
        migrations.DeleteModel(
            name='Qna_Posting',
        ),
    ]
