# Generated by Django 2.2.5 on 2022-04-13 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('password',
                 models.CharField(max_length=128,
                                  verbose_name='password')),
                ('last_login',
                 models.DateTimeField(blank=True,
                                      null=True,
                                      verbose_name='last login')),
                ('username',
                 models.CharField(blank=True,
                                  max_length=150,
                                  unique=True)),
                ('name',
                 models.CharField(max_length=128)),
                ('email',
                 models.EmailField(max_length=128,
                                   unique=True)),
                ('date_joined',
                 models.DateField(default=datetime.datetime.now)),
                ('is_active',
                 models.IntegerField(blank=True,
                                     null=True)),
                ('is_admin',
                 models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
